package net.herbertkb.wumpus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cave implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Cave() {
    }




}