package net.herbertkb.wumpus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int roomId;

	public Pit() {
	}

	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	public Pit(int roomId) {
		this.roomId = roomId;
	}

}