package net.herbertkb.wumpus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Player implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int roomId;
	private int arrowsLeft;

	public Player() {
	}

	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	public int getArrowsLeft() {
		return this.arrowsLeft;
	}

	public void setArrowsLeft(int arrowsLeft) {
		this.arrowsLeft = arrowsLeft;
	}

	public Player(int roomId, int arrowsLeft) {
		this.roomId = roomId;
		this.arrowsLeft = arrowsLeft;
	}

}